console.log('='.repeat(60));
console.log('Mandi Tracker TWA - Project Information');
console.log('='.repeat(60));
console.log('');
console.log('📱 Android TWA App for: https://mandi-tracker.vercel.app/');
console.log('');
console.log('Project Structure:');
console.log('  ├── app/                    - Android app module');
console.log('  ├── .github/workflows/      - GitHub Actions CI/CD');
console.log('  ├── build.gradle            - Root build configuration');
console.log('  └── assetlinks.json         - Digital Asset Links');
console.log('');
console.log('Build Instructions:');
console.log('  This project builds on GitHub Actions automatically.');
console.log('  Push to main/master branch to trigger a build.');
console.log('');
console.log('GitHub Actions Workflow:');
console.log('  - Builds release APK and AAB files');
console.log('  - Signs with your keystore (configure secrets)');
console.log('  - Uploads artifacts for download');
console.log('  - Creates releases for version tags');
console.log('');
console.log('Required GitHub Secrets:');
console.log('  - SIGNING_KEY           (Base64 encoded keystore)');
console.log('  - KEY_ALIAS             (Keystore alias)');
console.log('  - KEY_STORE_PASSWORD    (Keystore password)');
console.log('  - KEY_PASSWORD          (Key password)');
console.log('');
console.log('Digital Asset Links:');
console.log('  Host assetlinks.json at:');
console.log('  https://mandi-tracker.vercel.app/.well-known/assetlinks.json');
console.log('');
console.log('App Configuration:');
console.log('  Package: com.mandi.tracker');
console.log('  URL: https://mandi-tracker.vercel.app/');
console.log('  Colors: Green theme (#4CAF50)');
console.log('');
console.log('='.repeat(60));
console.log('ℹ️  This is an Android project. Builds happen on GitHub Actions.');
console.log('='.repeat(60));
